### ISSUE TITLE
How to create/verify 6 digit Google Authenticator using this library

### ISSUE THREAD

**Issue by yesvivek** [JamesxX/TOTP#1]
Google Authenticator produces 6 digit TOTP code. Could that be validated with this library? 
I get TOTP::generate(time) returning 6c5a4269895008e72b042965df06d51c8cbbd007, is it possible to convert it to 6-digit code?

**Comment by jamesrswift** [comment]
No, this library doesn't follow any standards. Even if it did, you wouldn't be provided with the required information to validate it yourself.
